version: '2'

services:
  web:
    build: ./nginx
    volumes:
      - .:/usr/share/nginx/html/
    ports:
      - 80:80
  webpack:
    build: ./app
    command: webpack-dev-server --config webpack.hot.config.js --hot --progress --inline --host=0.0.0.0
    volumes:
      - ./app:/var/app
      - /var/app/node_modules
    ports:
      - 8080:8080